# coding: utf-8

# flake8: noqa

"""
    Trust Score API

    API for fetching trust scores

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ApiApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Reputation",
    "TokenObtainPair",
    "TokenRefresh",
    "TrustScore",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from openapi_client.api.api_api import ApiApi as ApiApi
    
    # import ApiClient
    from openapi_client.api_response import ApiResponse as ApiResponse
    from openapi_client.api_client import ApiClient as ApiClient
    from openapi_client.configuration import Configuration as Configuration
    from openapi_client.exceptions import OpenApiException as OpenApiException
    from openapi_client.exceptions import ApiTypeError as ApiTypeError
    from openapi_client.exceptions import ApiValueError as ApiValueError
    from openapi_client.exceptions import ApiKeyError as ApiKeyError
    from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
    from openapi_client.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from openapi_client.models.reputation import Reputation as Reputation
    from openapi_client.models.token_obtain_pair import TokenObtainPair as TokenObtainPair
    from openapi_client.models.token_refresh import TokenRefresh as TokenRefresh
    from openapi_client.models.trust_score import TrustScore as TrustScore
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from openapi_client.api.api_api import ApiApi as ApiApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.reputation import Reputation as Reputation
from openapi_client.models.token_obtain_pair import TokenObtainPair as TokenObtainPair
from openapi_client.models.token_refresh import TokenRefresh as TokenRefresh
from openapi_client.models.trust_score import TrustScore as TrustScore

""",
            name=__name__,
            doc=__doc__,
        )
    )
