# coding: utf-8

# flake8: noqa
"""
    Trust Score API

    API for fetching trust scores

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from openapi_client.models.reputation import Reputation
    from openapi_client.models.token_obtain_pair import TokenObtainPair
    from openapi_client.models.token_refresh import TokenRefresh
    from openapi_client.models.trust_score import TrustScore
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from openapi_client.models.reputation import Reputation
from openapi_client.models.token_obtain_pair import TokenObtainPair
from openapi_client.models.token_refresh import TokenRefresh
from openapi_client.models.trust_score import TrustScore

""",
            name=__name__,
            doc=__doc__,
        )
    )
