# coding: utf-8

"""
    Trust Score API

    API for fetching trust scores

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_api import ApiApi


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiApi()

    def tearDown(self) -> None:
        pass

    def test_api_reputation_collect_create(self) -> None:
        """Test case for api_reputation_collect_create

        """
        pass

    def test_api_reputation_reputation_list(self) -> None:
        """Test case for api_reputation_reputation_list

        """
        pass

    def test_api_reputation_reputation_retrieve(self) -> None:
        """Test case for api_reputation_reputation_retrieve

        """
        pass

    def test_api_reputation_retrieve(self) -> None:
        """Test case for api_reputation_retrieve

        """
        pass

    def test_api_schema_retrieve(self) -> None:
        """Test case for api_schema_retrieve

        """
        pass

    def test_api_token_create(self) -> None:
        """Test case for api_token_create

        """
        pass

    def test_api_token_refresh_create(self) -> None:
        """Test case for api_token_refresh_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
