# coding: utf-8

"""
    Trust Score API

    API for fetching trust scores

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reputation import Reputation

class TestReputation(unittest.TestCase):
    """Reputation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Reputation:
        """Test Reputation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Reputation`
        """
        model = Reputation()
        if include_optional:
            return Reputation(
                id = 56,
                user = 56,
                transaction = 1.337,
                social_signals = 1.337,
                blockchain = 1.337,
                score = '',
                explanation = ''
            )
        else:
            return Reputation(
                id = 56,
                user = 56,
                score = '',
                explanation = '',
        )
        """

    def testReputation(self):
        """Test Reputation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
