# Generated by Django 5.2.6 on 2025-09-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trustscore',
            old_name='last_updated',
            new_name='updated_at',
        ),
    ]
