# Generated by Django 5.2.6 on 2025-09-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0004_reputation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reputation',
            old_name='feedback',
            new_name='blockchain',
        ),
        migrations.RenameField(
            model_name='reputation',
            old_name='transactions',
            new_name='transaction',
        ),
    ]
